export enum stores {
	ALERT          = 'alertStore',
	BLOG           = 'blogStore',
	CHAT           = 'chatStore',
	CLOUDFLARE     = 'cloudflareStore',
	COUNTER        = 'counterStore',
	FILE           = 'fileStore',
	INTEREST_CHECK = 'interestCheckStore',
	JSON_RECORDS   = 'jsonRecordsStore',
	JSON           = 'jsonStore',
	MENU           = 'menuStore',
	NODE           = 'nodeStore',
	NOTIFICATIONS  = 'notificationsStore',
	PAGE           = 'pageStore',
	ROLE           = 'roleStore',
	SETTINGS       = 'settingsStore',
	SHOP           = 'shopStore',
	TASK_COMMENT   = 'taskCommentStore',
	TODO           = 'todoStore',
	USERS          = 'usersStore',
	USER           = 'userStore'
}